# -*- coding: utf-8 -*-
"""COVID-19 Data Analysis & Dashboard System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsdB9nGDdDSR5PK3xir_2Ks4yWlIVEMy

Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Load Dataset"""

df = pd.read_csv("/content/covid_19_clean_complete.csv")

"""Select Required Columns"""

df = df[['Date', 'Country/Region', 'Confirmed',
         'Deaths', 'Recovered', 'Active']]

"""Data Cleaning"""

df['Date'] = pd.to_datetime(df['Date'])
df.drop_duplicates(inplace=True)
df.fillna(0, inplace=True)

"""Display Dataset"""

print("Dataset Shape:", df.shape)
print(df.head())

"""Descriptive Statistics"""

print("\nTotal Confirmed Cases:", df['Confirmed'].sum())
print("Total Deaths:", df['Deaths'].sum())
print("Total Recovered:", df['Recovered'].sum())

"""Country Selection"""

country = "India"

country_df = df[df['Country/Region'] == country]

"""Line Chart"""

plt.figure(figsize=(10,5))
plt.plot(country_df['Date'],
         country_df['Confirmed'])

plt.title(f'Confirmed Cases Over Time - {country}')
plt.xlabel("Date")
plt.ylabel("Confirmed Cases")
plt.xticks(rotation=45)
plt.show()

"""Top 10 Affected Countries"""

top_countries = (
    df.groupby('Country/Region')['Confirmed']
    .max()
    .sort_values(ascending=False)
    .head(10)
)

plt.figure(figsize=(10,5))
top_countries.plot(kind='bar')

plt.title("Top 10 Affected Countries")
plt.xlabel("Country")
plt.ylabel("Confirmed Cases")
plt.show()

"""Pie Chart"""

latest = country_df.iloc[-1]

plt.figure(figsize=(6,6))

plt.pie(
    [latest['Active'],
     latest['Recovered'],
     latest['Deaths']],
    labels=['Active','Recovered','Deaths'],
    autopct='%1.1f%%'
)

plt.title(f'COVID Case Distribution - {country}')
plt.show()

"""Scatter Plot"""

plt.figure(figsize=(8,5))

plt.scatter(
    country_df['Confirmed'],
    country_df['Deaths']
)

plt.title("Confirmed vs Deaths")
plt.xlabel("Confirmed")
plt.ylabel("Deaths")
plt.show()

"""Heatmap"""

corr = country_df[
    ['Confirmed','Deaths',
     'Recovered','Active']
].corr()

plt.figure(figsize=(8,5))

sns.heatmap(
    corr,
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()